### ISSUE TITLE
Message "Kein aktuellen Daten"

### ISSUE THREAD

**Issue by tobru** [DP-3T/dp3t-app-android-ch#249]
Since recently I get the message "Keine aktuellen Daten. Seit einiger Zeit konnten die Meldungen nicht synchronisiert werden. Stellen Sie sicher, dass ihr Mobiltelefon mit dem Internet verbunden ist. (LOST)" and further below `RTSENLOST`. I also get a message that I need to have more recent Google Play services, otherwise the app doesn't work.

I'm using microG (v0.2.13.203915) on LineageOS and until (I guess) the recent SwissCovid app update to 1.2.0 it used to work. Of course I'm aware that this is an unsupported way of using SwissCovid, but nevertheless I'd like to figure out what's wrong and eventually report it to microG to improve their code.

I tried to get some information what's going on by using `adb logcat` but there are no obvious error messages from SwissCovid app. Is there a debug mode available?

One error I catched, but I'm unsure if this is the root cause here:

```
11-07 20:13:56.527  1773 12112 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms&pcampaignid=gcore_12451000--ch.admin.bag.dp3t-12000 flg=0x80000 pkg=com.android.vending} from uid 10208
11-07 20:13:56.528 24831 24831 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-07 20:13:56.528 24831 24831 E AndroidRuntime: FATAL EXCEPTION: main
11-07 20:13:56.528 24831 24831 E AndroidRuntime: Process: ch.admin.bag.dp3t, PID: 24831
11-07 20:13:56.528 24831 24831 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.admin.bag.dp3t/com.google.android.gms.common.api.GoogleApiActivity}: android.content.ActivityNotFoundException: No Activity found to handle null
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: No Activity found to handle null
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResultInner(Activity.java:5473)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResult(Activity.java:5439)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.Activity.startIntentSenderForResult(Activity.java:5406)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at com.google.android.gms.common.api.GoogleApiActivity.onCreate(com.google.android.gms:play-services-base@@17.2.1:12)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7824)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7813)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
11-07 20:13:56.528 24831 24831 E AndroidRuntime: 	... 11 more
```

**Comment by tobru** [comment]
It looks like this is caused by the lack of "ExposureWindow mode" in microG, see https://github.com/microg/android_packages_apps_GmsCore/issues/1168 and comment https://github.com/microg/android_packages_apps_GmsCore/issues/1258#issuecomment-723655745.

Of course it would be great when the Swiss people capable of doing it would support the effort of @mar-v-in with microG but as this is certainly out of scope of this issue I'll close it.
