### ISSUE TITLE
app crashes when clicking the google play services update notification

### ISSUE THREAD

**Issue by tingsu** [DP-3T/dp3t-app-android-ch#98]
Bug description
- The app crashes when clicking the google play services update notification 

Info
- Android 9.0
- SwissCovid App Version 1.0.3-pilot (Installed by Google Play Store)

Crash stack
```
 FATAL EXCEPTION: main
 Process: ch.admin.bag.dp3t, PID: 8692
 java.lang.RuntimeException: Unable to start activity ComponentInfo{ch.admin.bag.dp3t/com.google.android.gms.common.api.GoogleApiActivity}: android.content.ActivityNotFoundException: No Activity found to handle null
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
 	at android.os.Handler.dispatchMessage(Handler.java:107)
 	at android.os.Looper.loop(Looper.java:214)
 	at android.app.ActivityThread.main(ActivityThread.java:7356)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
 Caused by: android.content.ActivityNotFoundException: No Activity found to handle null
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2051)
 	at android.app.Activity.startIntentSenderForResultInner(Activity.java:5455)
 	at android.app.Activity.startIntentSenderForResult(Activity.java:5421)
 	at android.app.Activity.startIntentSenderForResult(Activity.java:5388)
 	at com.google.android.gms.common.api.GoogleApiActivity.onCreate(com.google.android.gms:play-services-base@@17.2.1:12)
 	at android.app.Activity.performCreate(Activity.java:7802)
 	at android.app.Activity.performCreate(Activity.java:7791)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
 	... 11 more
```

Reproducing video

![20200614_214334](https://user-images.githubusercontent.com/3156978/84602518-3ec36700-ae88-11ea-9406-8c04cf33c0a0.gif)

**Comment by tingsu** [comment]
any update? thanks.

**Comment by simonroesch** [comment]
This notification is generated by Google PlayServices and not SwissCovid. I tried to reproduce the problem on two phones but without success. What is the version of your Google PlayServices?

**Comment by tingsu** [comment]
Thanks for your reply @simonroesch. I guess the root cause is that I run on a device that does not have Google Play. SwissCovid should have an additional check.

**Comment by simonroesch** [comment]
Ok I see, unfortunately, we cannot suppress this notification, but I will forward the feedback to Google. What happens later in the Onboarding process if you try to enable ExposureNotifications (ignoring the notification when starting the app).

**Comment by tingsu** [comment]
Okay, I understand what you mean. Is it possible to check the existence of Google Play on the device before sending the notification (to update the Google Play Services)? If Google Play does not exists, give an additional message (or maybe a toast) to alert the user.

**Comment by simonroesch** [comment]
Let me check what exactly triggers the notification, then we maybe can wrap that in a check for the presence of Google PlayServices.

**Comment by simonroesch** [comment]
OK, found the problem. The SDK checks upon initialization if ExposureNotifications are enabled, which makes a call to the Google PlayServices and triggers the notification if they are not up to date. If we prevent this call when an update is needed, the notification will not show up. This is fixed in https://github.com/DP-3T/dp3t-sdk-android/pull/164
